export const currenciesData = [
  {
    name: 'US Dollar',
    abbreviation: 'USD',
    currencySymbol: '\u0024',
    currencyFlag: 'http://www.geonames.org/flags/l/us.gif',
  },
  {
    name: 'Euro',
    abbreviation: 'EUR',
    currencySymbol: '\u20AC',
    currencyFlag:
      'https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg',
  },
  {
    name: 'Japanese Yen',
    abbreviation: 'JPY',
    currencySymbol: '\u00A5',
    currencyFlag: 'http://www.geonames.org/flags/l/jp.gif',
  },
  {
    name: 'British Pound',
    abbreviation: 'GBP',
    currencySymbol: '\u00A3',
    currencyFlag: 'http://www.geonames.org/flags/l/uk.gif',
  },
  {
    name: 'Australian Dollar',
    abbreviation: 'AUD',
    currencySymbol: '\u0024',
    currencyFlag: 'http://www.geonames.org/flags/l/au.gif',
  },
  {
    name: 'Canadian Dollar',
    abbreviation: 'CAD',
    currencySymbol: '\u0024',
    currencyFlag: 'http://www.geonames.org/flags/l/ca.gif',
  },
  {
    name: 'Swiss Franc',
    abbreviation: 'CHF',
    currencySymbol: '\u0043\u0048\u0046',
    currencyFlag: 'http://www.geonames.org/flags/l/ch.gif',
  },
  {
    name: 'Chinese Yuan Renminbi',
    abbreviation: 'CNY',
    currencySymbol: '\u00A5',
    currencyFlag: 'http://www.geonames.org/flags/l/cn.gif',
  },
  {
    name: 'Swedish Krona',
    abbreviation: 'SEK',
    currencySymbol: '\u006B\u0072',
    currencyFlag: 'http://www.geonames.org/flags/l/se.gif',
  },
  {
    name: 'New Zealand Dollar',
    abbreviation: 'NZD',
    currencySymbol: '\u0024',
    currencyFlag: 'http://www.geonames.org/flags/l/nz.gif',
  },
  {
    name: 'Mexican Peso',
    abbreviation: 'MXN',
    currencySymbol: '\u0024',
    currencyFlag: 'http://www.geonames.org/flags/l/mx.gif',
  },
  {
    name: 'Singapore Dollar',
    abbreviation: 'SGD',
    currencySymbol: '\u0024',
    currencyFlag: 'http://www.geonames.org/flags/l/sg.gif',
  },
  {
    name: 'Hong Kong Dollar',
    abbreviation: 'HKD',
    currencySymbol: '\u0024',
    currencyFlag: 'http://www.geonames.org/flags/l/hk.gif',
  },
  {
    name: 'Norwegian Krone',
    abbreviation: 'NOK',
    currencySymbol: '\u006B\u0072',
    currencyFlag: 'http://www.geonames.org/flags/l/no.gif',
  },
  {
    name: 'South Korean Won',
    abbreviation: 'KRW',
    currencySymbol: '\u20A9',
    currencyFlag: 'http://www.geonames.org/flags/l/kr.gif',
  },
  {
    name: 'Turkish Lira',
    abbreviation: 'TRY',
    currencySymbol: '\u20BA',
    currencyFlag: 'http://www.geonames.org/flags/l/tr.gif',
  },
  {
    name: 'Russian Ruble',
    abbreviation: 'RUB',
    currencySymbol: '\u20BD',
    currencyFlag: 'http://www.geonames.org/flags/l/ru.gif',
  },
  {
    name: 'Indian Rupee',
    abbreviation: 'INR',
    currencySymbol: '\u20B9',
    currencyFlag: 'http://www.geonames.org/flags/l/in.gif',
  },
  {
    name: 'Brazilian Real',
    abbreviation: 'BRL',
    currencySymbol: '\u0052\u0024',
    currencyFlag: 'http://www.geonames.org/flags/l/br.gif',
  },
  {
    name: 'South African Rand',
    abbreviation: 'ZAR',
    currencySymbol: '\u0052',
    currencyFlag: 'http://www.geonames.org/flags/l/za.gif',
  },
  {
    name: 'Philippine Peso',
    abbreviation: 'PHP',
    currencySymbol: '\u20B1',
    currencyFlag: 'http://www.geonames.org/flags/l/ph.gif',
  },
  {
    name: 'Czech Koruna',
    abbreviation: 'CZK',
    currencySymbol: '\u004B\u010D',
    currencyFlag: 'http://www.geonames.org/flags/l/cz.gif',
  },
  {
    name: 'Indonesian Rupiah',
    abbreviation: 'IDR',
    currencySymbol: '\u0052\u0070',
    currencyFlag: 'http://www.geonames.org/flags/l/id.gif',
  },
  {
    name: 'Malaysian Ringgit',
    abbreviation: 'MYR',
    currencySymbol: '\u0052\u004D',
    currencyFlag: 'http://www.geonames.org/flags/l/my.gif',
  },
  {
    name: 'Hungarian Forint',
    abbreviation: 'HUF',
    currencySymbol: '\u0046\u0074',
    currencyFlag: 'http://www.geonames.org/flags/l/hu.gif',
  },
  {
    name: 'Icelandic Krona',
    abbreviation: 'ISK',
    currencySymbol: '\u006B\u0072',
    currencyFlag: 'http://www.geonames.org/flags/l/is.gif',
  },
  {
    name: 'Croatian Kuna',
    abbreviation: 'HRK',
    currencySymbol: '\u006B\u006E',
    currencyFlag: 'http://www.geonames.org/flags/l/hr.gif',
  },
  {
    name: 'Bulgarian Lev',
    abbreviation: 'BGN',
    currencySymbol: '\u043B\u0432',
    currencyFlag: 'http://www.geonames.org/flags/l/bg.gif',
  },
  {
    name: 'Romanian Leu',
    abbreviation: 'RON',
    currencySymbol: '\u006C\u0065\u0069',
    currencyFlag: 'http://www.geonames.org/flags/l/ro.gif',
  },
  {
    name: 'Danish Krone',
    abbreviation: 'DKK',
    currencySymbol: '\u006B\u0072',
    currencyFlag: 'http://www.geonames.org/flags/l/dk.gif',
  },
  {
    name: 'Thai Baht',
    abbreviation: 'THB',
    currencySymbol: '\u0E3F',
    currencyFlag: 'http://www.geonames.org/flags/l/th.gif',
  },
  {
    name: 'Polish Zloty',
    abbreviation: 'PLN',
    currencySymbol: '\u007A\u0142',
    currencyFlag: 'http://www.geonames.org/flags/l/pl.gif',
  },
  {
    name: 'Israeli Shekel',
    abbreviation: 'ILS',
    currencySymbol: '\u20AA',
    currencyFlag: 'http://www.geonames.org/flags/l/il.gif',
  },
];
